#!/usr/bin/env bash
set -e

# Function to install Ansible
install_ansible() {
  echo "Installing Ansible..."
  sudo pip3 install --upgrade pip
  pip3 install ansible
  echo "Ansible installed successfully."
}

# Check if Ansible is installed
if ! command -v ansible &> /dev/null; then
  echo "Ansible is not installed."
  read -p "Do you want to install Ansible? [y/N] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    install_ansible
  else
    echo "Ansible installation aborted. Exiting."
    exit 1
  fi
fi

# Check if all argument is supplied, if so use "all" tags
if [ "${1}" == "-all" ]; then
  tags="all"
else
  # Otherwise, use value from 1st argument, defaulting to "stow"
  tags="${1:-stow}"
fi

# Get the full directory path of the script
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# Install required Ansible roles
echo "Installing required Ansible roles..."
ANSIBLE_CONFIG=${SCRIPTPATH}/ansible.cfg ansible-galaxy install -r ${SCRIPTPATH}/requirements.yml &>/dev/null
echo "Roles installed successfully."

# Execute the Ansible playbook
echo "Running Ansible playbook..."
ANSIBLE_CONFIG=${SCRIPTPATH}/ansible.cfg ansible-playbook ${SCRIPTPATH}/playbook.yml --ask-become-pass --tags "${tags}"

# Notification if terminal-notifier is installed
if command -v terminal-notifier &> /dev/null; then
  terminal-notifier -title "dotfiles: Bootstrap complete" -message "Successfully set up environment."
fi

echo "Bootstrap process completed successfully."

